# Generated by Django 5.0.4 on 2024-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorregdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=200)),
                ('wdays', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
