# Generated by Django 5.0.4 on 2024-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patientdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
