# Generated by Django 5.0.4 on 2024-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentno', models.CharField(max_length=200)),
                ('departmentname', models.CharField(max_length=200)),
                ('departmenthead', models.CharField(max_length=200)),
            ],
        ),
    ]
