# Generated by Django 5.0.4 on 2024-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_patientdb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='dob',
            field=models.DateField(max_length=200),
        ),
    ]
